from django.urls import path
from . import views


urlpatterns = [

    path(
        route='',
        view=views.Principal.as_view(),
        name=''
    ),
    path(
        route='get_select_copy',
        view=views.PostGetSelectCopy.as_view(),
        name='get_select_copy'
    ),
    path(
        route='get_select_fusion',
        view=views.PostGetSelectFusion.as_view(),
        name='get_select_fusion'
    ),
    path(
        route='active_deactive_datalist',
        view=views.PostActiveDeactiveDataList.as_view(),
        name='active_deactive_datalist'
    ),
    path(
        route='delete_datalist',
        view=views.PostDeleteDataList.as_view(),
        name='delete_datalist'
    ),
    path(
        route='get_last_id',
        view=views.PostGetLastCodeDataList.as_view(),
        name='get_last_id'
    ),
    path(
        route='total_litro',
        view=views.PostTotalLitroId.as_view(),
        name='total_litro'
    ),
    path(
        route='total_litro_ref',
        view=views.PostTotalLitroIdRef.as_view(),
        name='total_litro_ref'
    ),
    path(
        route='total_cliente',
        view=views.PostTotaClienteId.as_view(),
        name='total_cliente'
    ),
    path(
        route='total_cliente_ref',
        view=views.PostTotaClienteIdRef.as_view(),
        name='total_cliente_ref'
    ),
    path(
        route='total_determinante',
        view=views.PostTotaDeterminantesId.as_view(),
        name='total_determinante'
    ),
    path(
        route='total_determinante_ref',
        view=views.PostTotaDeterminantesIdRef.as_view(),
        name='total_determinante_ref'
    ),
    path(
        route='total_productos_ref',
        view=views.PostTotaProductosIdRef.as_view(),
        name='total_productos_ref'
    ),
    path(
        route='copy_datalist',
        view=views.PostCopyDataList.as_view(),
        name='copy_datalist'
    ),
    path(
        route='fusion_datalist',
        view=views.PostFusionDataList.as_view(),
        name='fusion_datalist'
    ),
    path(
        route='datatables_header',
        view=views.DataTablesHeader.as_view(),
        name='datatables_header'
    ),
    path(
        route='datatables_datasheet',
        view=views.DataTablesDatasheets.as_view(),
        name='datatables_datasheet'
    ),
    path(
        route='datatables_datasheet_line',
        view=views.DataTablesDatasheetsLine.as_view(),
        name='datatables_datasheet_line'
    ),
    path(
        route='showid',
        view=views.ShowId,
        name='showid'
    ),
    path(
        route='showref',
        view=views.ShowRef,
        name='showref'
    ),

]