from django.urls import path
from . import views


urlpatterns = [

    path(
        route='panel',
        view=views.Principal.as_view(),
        name='panel'
    ),
    path(
        route='type',
        view=views.Type.as_view(),
        name='type'
    ),
    path(
        route='inbox',
        view=views.Inbox.as_view(),
        name='inbox'
    ),
    path(
        route='create_type',
        view=views.CreateTypeNotify.as_view(),
        name='create_type'
    ),
    path(
        route='create_notify',
        view=views.CreateNotify.as_view(),
        name='create_notify'
    ),
    path(
        route='datatables_type_notify',
        view=views.DatatablesTypeNotify.as_view(),
        name='datatables_type_notify'
    ),
    path(
        route='datatables_notify',
        view=views.DatatablesNotify.as_view(),
        name='datatables_notify'
    ),
    path(
        route='datatables_notify_inbox',
        view=views.DatatablesNotifyInbox.as_view(),
        name='datatables_notify_inbox'
    ),
    path(
        route='datatables_notify_important',
        view=views.DatatablesNotifyImportant.as_view(),
        name='datatables_notify_important'
    ),
    path(
        route='datatables_notify_trash',
        view=views.DatatablesNotifyTrash.as_view(),
        name='datatables_notify_trash'
    ),
    path(
        route='datatables_notify_send',
        view=views.DatatablesNotifySend.as_view(),
        name='datatables_notify_send'
    ),
    path(
        route='showid',
        view=views.ShowId,
        name='showid'
    ),
    path(
        route='labelshow',
        view=views.LabelShow,
        name='labelshow'
    ),
    path(
        route='post_change_important',
        view=views.PostChangeImportant.as_view(),
        name='post_change_important'
    ),
    path(
        route='post_change_trash',
        view=views.PostChangeTrash.as_view(),
        name='post_change_trash'
    ),
    path(
        route='post_change_active',
        view=views.PostChangeActive.as_view(),
        name='post_change_active'
    ),
    path(
        route='post_change_deactive',
        view=views.PostChangeDeactive.as_view(),
        name='post_change_deactive'
    ),
    path(
        route='post_change_active_type',
        view=views.PostChangeActiveType.as_view(),
        name='post_change_active_type'
    ),
    path(
        route='post_change_deactive_type',
        view=views.PostChangeDeactiveType.as_view(),
        name='post_change_deactive_type'
    ),
    path(
        route='inbox',
        view=views.GetNotifyInbox.as_view(),
        name='inbox'
    ),
    path(
        route='important',
        view=views.GetNotifyImportant.as_view(),
        name='important'
    ),
    path(
        route='send',
        view=views.GetNotifySend.as_view(),
        name='send'
    ),
    path(
        route='trash',
        view=views.GetNotifyTrash.as_view(),
        name='trash'
    ),
    path(
        route='one',
        view=views.PostChangeActive.as_view(),
        name='one'
    ),
    path(
        route='new',
        view=views.New.as_view(),
        name='new'
    ),

   

]