# Generated by Django 2.2 on 2024-11-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('current', 'Actual'), ('model', 'Modelo'), ('models', 'Modelos'), ('semilla', 'Semilla')], default='current', max_length=20)),
                ('tcurrent_id', models.IntegerField()),
                ('tcurrent_code', models.CharField(default='', max_length=100)),
                ('tcurrent_fields', models.TextField()),
                ('tmodel_id', models.IntegerField()),
                ('tmodel_code', models.CharField(default='', max_length=100)),
                ('tmodel_field', models.CharField(default='', max_length=100)),
                ('tmodel_fields', models.TextField()),
                ('tmodels_id', models.IntegerField()),
                ('tmodels_code', models.TextField()),
                ('tmodels_fields', models.TextField()),
                ('tseed_id', models.IntegerField()),
                ('tseed_code', models.TextField()),
                ('action', models.CharField(choices=[('equal', 'Igual a'), ('greaterthan', 'Mayor que'), ('lessthan', 'Menor que'), ('contain', 'Contiene'), ('notcontain', 'No contiene'), ('lefteq', 'Empieza con'), ('rigtheq', 'Termina con'), ('notdefined', 'No definido'), ('defined', 'Definido')], default='equal', max_length=20)),
                ('eval', models.CharField(choices=[('value', 'Valor'), ('field', 'Campo'), ('fields', 'Campos'), ('model', 'Modelo'), ('models', 'Modelos')], default='value', max_length=20)),
                ('avalue', models.CharField(default='', max_length=500)),
                ('avalues', models.TextField()),
                ('afield', models.CharField(default='', max_length=200)),
                ('afields', models.TextField()),
                ('amodel_id', models.IntegerField()),
                ('amodel_code', models.CharField(default='', max_length=100)),
                ('amodel_field', models.CharField(default='', max_length=100)),
                ('amodel_fields', models.TextField()),
                ('amodels_id', models.IntegerField()),
                ('amodels_code', models.TextField()),
                ('amodels_fields', models.TextField()),
                ('active', models.SmallIntegerField(default=1)),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('internal', 'Interno'), ('external', 'Externo'), ('file', 'CSV'), ('api', 'API')], default='internal', max_length=20)),
                ('tinternal_code', models.CharField(default='', max_length=100)),
                ('tinternal_model', models.CharField(default='', max_length=100)),
                ('tinternal_fields', models.TextField()),
                ('texternal_host', models.CharField(default='', max_length=100)),
                ('texternal_user', models.CharField(default='', max_length=100)),
                ('texternal_password', models.CharField(default='', max_length=100)),
                ('texternal_port', models.CharField(default='', max_length=100)),
                ('texternal_db', models.CharField(default='', max_length=100)),
                ('texternal_query', models.CharField(default='', max_length=100)),
                ('texternal_code', models.CharField(default='', max_length=100)),
                ('texternal_model', models.CharField(default='', max_length=100)),
                ('texternal_fields', models.TextField()),
                ('tfile_code', models.CharField(default='', max_length=100)),
                ('tfile_model', models.CharField(default='', max_length=100)),
                ('tfile_fields', models.TextField()),
                ('tfile_path', models.TextField()),
                ('tfile_binary', models.BinaryField()),
                ('tapi_code', models.CharField(default='', max_length=100)),
                ('tapi_model', models.CharField(default='', max_length=100)),
                ('tapi_fields', models.TextField()),
                ('tapi_endpoint', models.TextField()),
                ('active', models.SmallIntegerField(default=1)),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
    ]
