# Generated by Django 2.2 on 2024-11-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20241106_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='tapi_model',
        ),
        migrations.RemoveField(
            model_name='model',
            name='tfile_model',
        ),
    ]
