# Generated by Django 2.2 on 2024-11-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_auto_20241106_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='tfile_binary',
            field=models.FileField(max_length=500, upload_to='rules/csv'),
        ),
    ]
