# Generated by Django 2.2 on 2024-11-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_auto_20241106_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='type',
            field=models.CharField(choices=[('internal', 'Interno'), ('external', 'Postgresql'), ('file', 'CSV'), ('api', 'API')], default='internal', max_length=20),
        ),
    ]
