# Generated by Django 2.2 on 2024-11-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_model_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='delete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
