# Generated by Django 2.2 on 2024-11-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_auto_20241111_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='tapi_structure',
            field=models.TextField(default=''),
        ),
    ]
