# Generated by Django 2.2 on 2024-11-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_model_tapi_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='tmodels_id',
            field=models.TextField(),
        ),
    ]
