# Generated by Django 4.2 on 2025-01-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0015_alter_header_eval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='amodels_code',
        ),
        migrations.RemoveField(
            model_name='header',
            name='amodels_fields',
        ),
        migrations.RemoveField(
            model_name='header',
            name='amodels_id',
        ),
    ]
