# Generated by Django 4.2 on 2025-01-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_remove_header_amodels_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='avaluescomp',
            field=models.TextField(default=''),
        ),
    ]
