# Generated by Django 4.2 on 2025-01-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0017_header_avaluescomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='afieldscomp',
            field=models.TextField(default=''),
        ),
    ]
