# Generated by Django 4.2 on 2025-01-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0018_header_afieldscomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='amodel_fieldscomp',
            field=models.TextField(default=''),
        ),
    ]
