# Generated by Django 2.2 on 2024-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('volumen', models.FloatField(default=0.0, verbose_name='Volumén')),
                ('capacity_pallet', models.FloatField(default=0.0, verbose_name='Capacidad de tarimas')),
                ('active', models.SmallIntegerField(default=1)),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
    ]
