# Generated by Django 5.1.5 on 2025-01-20 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabEpicor01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_order', models.CharField(max_length=40, verbose_name='Orden de Embarque')),
                ('status', models.CharField(max_length=40, verbose_name='Estatus')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion de Ruta')),
                ('type_vehicle', models.CharField(max_length=40, verbose_name='Transporte')),
                ('destiny', models.CharField(max_length=40, verbose_name='Destino')),
                ('type_transport', models.CharField(max_length=40, verbose_name='Tipo de Unidad')),
                ('route_number', models.CharField(max_length=40, verbose_name='Numero de Ruta')),
                ('delivery_schedule', models.CharField(max_length=40, verbose_name='Horario Asigando')),
                ('liters', models.FloatField(verbose_name='Litros de la Ruta')),
                ('warehouse', models.CharField(max_length=40, verbose_name='Almacen')),
                ('delivery_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ruta')),
                ('transfer_guide', models.CharField(max_length=40, verbose_name='Guía de paquetera')),
            ],
        ),
        migrations.CreateModel(
            name='LinesEpicor01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Orden')),
                ('line', models.IntegerField(verbose_name='Linea')),
                ('rel', models.IntegerField(verbose_name='Relación')),
                ('header_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='api.cabepicor01')),
            ],
        ),
    ]
