# Generated by Django 2.2 on 2024-10-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, verbose_name='Folio')),
                ('ide', models.IntegerField(verbose_name='Identificador')),
                ('ref', models.CharField(max_length=40, verbose_name='Referencia Interna')),
                ('oc', models.IntegerField(verbose_name='Pedido')),
                ('invoice', models.CharField(max_length=40, verbose_name='Factura')),
                ('partner', models.CharField(max_length=160, verbose_name='Cuenta')),
                ('state', models.CharField(choices=[('SA', 'Sin asignar'), ('PO', 'Procesando'), ('AS', 'Asignado'), ('CO', 'Corregido')], default='SA', max_length=20, verbose_name='Estatus')),
                ('createdata_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('create_time', models.TimeField(auto_now_add=True, verbose_name='Hora de creación')),
                ('delivery_date', models.DateField(verbose_name='Fecha de entrega')),
                ('appointment_time', models.TimeField(verbose_name='Hora de creación')),
                ('comment', models.TextField(verbose_name='Comentarios adicionales')),
                ('pieces_received', models.FloatField(verbose_name='Piezas recibidas')),
                ('boxes_received', models.FloatField(verbose_name='Cajas recibidas')),
                ('pallets_received', models.FloatField(verbose_name='Cajas recibidas')),
                ('sku', models.CharField(max_length=10, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('site', models.CharField(max_length=20, verbose_name='Bodega')),
                ('origin_site', models.CharField(max_length=40, verbose_name='Nombre del origen')),
                ('delivery_name', models.TextField(verbose_name='Nombre del destino')),
                ('delivery_city', models.CharField(max_length=10, verbose_name='Estado del destino')),
                ('delivery_town', models.CharField(max_length=80, verbose_name='Municipio del destino')),
                ('delivery_location', models.CharField(max_length=80, verbose_name='Colonia del destino')),
                ('delivery_cp', models.CharField(max_length=10, verbose_name='CP del destino')),
                ('delivery_address', models.TextField(verbose_name='Dirección del destino')),
                ('delivery_latitude', models.FloatField(verbose_name='Latitud del destino')),
                ('delivery_length', models.FloatField(verbose_name='Longitud del destino')),
                ('type_service', models.CharField(max_length=10, verbose_name='Tipo de servicio')),
                ('type_order', models.CharField(max_length=20, verbose_name='Tipo de orden')),
                ('type_delivery', models.CharField(max_length=20, verbose_name='Tipo de entrega')),
                ('last_quation_delivery', models.TextField(verbose_name='Última solicitud de embarque')),
                ('last_delivery', models.TextField(verbose_name='Último embarque')),
                ('pieces', models.FloatField(verbose_name='Piezas')),
                ('boxes', models.FloatField(verbose_name='Cajas')),
                ('pallets', models.FloatField(verbose_name='Pallets')),
                ('responsible_rejection', models.CharField(max_length=40, verbose_name='Responsable del rechazo')),
                ('routing_status', models.CharField(choices=[('PR', 'Pendiente de envío a ruteo'), ('ES', 'En escenario'), ('AP', 'Aprobación'), ('RO', 'Ruteado'), ('IR', 'En ruta')], default='PR', max_length=40, verbose_name='Estatus de Ruteo')),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
    ]
