# Generated by Django 2.2 on 2024-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='type_action',
            field=models.CharField(choices=[('SA', 'Sin acciones'), ('FU', 'Fusionado'), ('CP', 'Copiado')], default='SA', max_length=40, verbose_name='Tipo de Accion'),
        ),
    ]
