# Generated by Django 2.2 on 2024-10-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0002_auto_20241016_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Folio')),
                ('state', models.CharField(choices=[('LI', 'Libre'), ('AS', 'Asignado'), ('AN', 'Analizado'), ('CL', 'Clasificado'), ('AP', 'Aprobado')], default='LI', max_length=20, verbose_name='Estado')),
                ('state_copy', models.CharField(choices=[('OR', ''), ('CP', 'Copiado'), ('CA', 'Copia')], default='OR', max_length=20, verbose_name='Estado copia')),
                ('state_fusion', models.CharField(choices=[('OR', ''), ('CP', 'Fusionado')], default='OR', max_length=20, verbose_name='Estado Fusión')),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
    ]
