# Generated by Django 2.2 on 2024-10-16 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0003_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='datasheet',
            name='header_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='datasheet.Header'),
        ),
    ]
