# Generated by Django 2.2 on 2024-10-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0005_relparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='id_partner',
            field=models.IntegerField(default=False, verbose_name='Cuenta'),
        ),
    ]
