# Generated by Django 2.2 on 2024-10-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0006_datasheet_id_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='id_prod',
            field=models.IntegerField(default=False, verbose_name='Id producto'),
        ),
    ]
