# Generated by Django 2.2 on 2024-10-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0007_datasheet_id_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='delivery_id',
            field=models.FloatField(default=False, verbose_name='Id destino'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='delivery_rfc',
            field=models.CharField(default='', max_length=20, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='package_type',
            field=models.CharField(default='', max_length=20, verbose_name='Tipo de paquete'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='product_sat',
            field=models.CharField(default='', max_length=20, verbose_name='UOM SAT'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='product_uom',
            field=models.CharField(default='', max_length=20, verbose_name='UOM'),
        ),
    ]
