# Generated by Django 2.2 on 2024-10-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0009_datasheet_product_uomt'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='incoterm',
            field=models.CharField(default='', max_length=40, verbose_name='Incocoterm'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='product_vol',
            field=models.FloatField(default=0.0, verbose_name='UDV'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='spo_qty',
            field=models.FloatField(default=0.0, verbose_name='Cantidad reportada'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='udv_total',
            field=models.FloatField(default=0.0, verbose_name='UDV Total'),
        ),
    ]
