# Generated by Django 2.2 on 2024-10-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0010_auto_20241017_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='planta',
            field=models.IntegerField(default=0, verbose_name='Planta'),
        ),
    ]
