# Generated by Django 2.2 on 2024-10-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0011_datasheet_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='delivery_city',
            field=models.CharField(max_length=50, verbose_name='Estado del destino'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sku',
            field=models.CharField(max_length=15, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='type_service',
            field=models.CharField(max_length=20, verbose_name='Tipo de servicio'),
        ),
    ]
