# Generated by Django 2.2 on 2024-10-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0012_auto_20241017_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='state_fusion',
            field=models.CharField(choices=[('OR', ''), ('FS', 'Fusionado')], default='OR', max_length=20, verbose_name='Estado Fusión'),
        ),
    ]
