# Generated by Django 2.2 on 2024-10-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0014_header_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='routing_status',
            field=models.CharField(choices=[('PR', 'Pendiente'), ('ES', 'Escenario'), ('AP', 'Aprobación'), ('RO', 'Ruteado'), ('IR', 'En ruta')], default='PR', max_length=40, verbose_name='Estatus de Ruteo'),
        ),
    ]
