# Generated by Django 2.2 on 2024-10-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0015_auto_20241021_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempNextCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=50, verbose_name='Llave')),
                ('value', models.CharField(default='', max_length=50, verbose_name='Llave')),
            ],
        ),
    ]
