# Generated by Django 2.2 on 2024-10-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0017_auto_20241025_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relparent',
            name='type',
            field=models.CharField(choices=[('CO', 'Copia'), ('FU', 'Fusión'), ('DV', 'Derivado'), ('GB', 'Agrupación'), ('TF', 'Transformación')], default='CO', max_length=20, verbose_name='Tipo'),
        ),
    ]
