# Generated by Django 2.2 on 2024-10-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0018_auto_20241025_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relparent',
            name='id_parent',
            field=models.IntegerField(),
        ),
    ]
