# Generated by Django 2.2 on 2024-10-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0019_auto_20241025_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='state_fusion',
            field=models.CharField(choices=[('OR', ''), ('FS', 'Fusionado'), ('BF', 'Base')], default='OR', max_length=20, verbose_name='Estado Fusión'),
        ),
    ]
