# Generated by Django 2.2 on 2024-10-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0020_auto_20241026_1227'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='header',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_blocking'),
        ),
    ]
