# Generated by Django 2.2 on 2024-11-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0021_auto_20241029_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
