# Generated by Django 2.2 on 2024-08-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='active',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='typenotify',
            name='active',
            field=models.SmallIntegerField(default=1),
        ),
    ]
