# Generated by Django 2.2 on 2024-08-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20240826_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='see',
            field=models.SmallIntegerField(default=0),
        ),
    ]
