# Generated by Django 2.2 on 2024-08-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20240827_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='notify',
            old_name='user_id',
            new_name='user',
        ),
    ]
