# Generated by Django 2.2 on 2024-08-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_auto_20240827_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.TypeNotify'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
