# Generated by Django 2.2 on 2024-08-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_auto_20240827_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='important',
            field=models.SmallIntegerField(default=0),
        ),
    ]
