# Generated by Django 2.2 on 2024-08-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0008_notify_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='trash',
            field=models.SmallIntegerField(default=0),
        ),
    ]
