# Generated by Django 2.2 on 2024-10-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0009_notify_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='to',
            field=models.SmallIntegerField(default=2),
        ),
    ]
