# Generated by Django 2.2 on 2024-11-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0010_auto_20241029_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
