# Generated by Django 2.2 on 2024-11-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('active', models.SmallIntegerField(default=1)),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('edos', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('number_code', models.IntegerField()),
                ('active', models.SmallIntegerField(default=1)),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('create_uid', models.IntegerField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
    ]
