from django.urls import path
from . import views


urlpatterns = [
    path(
        route='',
        view=views.Principal.as_view(),
        name=''
    ),
    path(
        route='edos',
        view=views.Estados.as_view(),
        name='edos'
    ),
    path(
        route='post_get_states',
        view=views.PostGetStates.as_view(),
        name='post_get_states'
    ),
    path(
        route='datatables_info_edos',
        view=views.DataTablesInfoEdos.as_view(),
        name='datatables_info_edos'
    ),
    path(
        route='datatables_info_model',
        view=views.DataTablesInfoModel.as_view(),
        name='datatables_info_model'
    ),
    path(
        route='showidedos',
        view=views.ShowIdEdos,
        name='showidedos'
    ),
    path(
        route='showidm',
        view=views.ShowIdModel,
        name='showidm'
    ),
    path(
        route='active_toggle_rules',
        view=views.DatatablesActiveToggleRules.as_view(),
        name='active_toggle_rules'
    ),
    path(
        route='active_toggle_rules_edos',
        view=views.DatatablesActiveToggleRulesEdos.as_view(),
        name='active_toggle_rules_edos'
    ),
    path(
        route='active_toggle_rules_model',
        view=views.DatatablesActiveToggleRulesModel.as_view(),
        name='active_toggle_rules_model'
    ),
    path(
        route='delete_rules',
        view=views.DatatablesDeleteRules.as_view(),
        name='delete_rules'
    ),
    path(
        route='delete_rules_edos',
        view=views.DatatablesDeleteRulesEdos.as_view(),
        name='delete_rules_edos'
    ),
    path(
        route='delete_rules_model',
        view=views.DatatablesDeleteRulesModel.as_view(),
        name='delete_rules_model'
    ),
    path(
        route='update_model_edos',
        view=views.UpdateModelEdos.as_view(),
        name='update_model_edos'
    ),
    path(
        route='update_model_model',
        view=views.UpdateModelModel.as_view(),
        name='update_model_model'
    )
]