# Generated by Django 2.2 on 2024-08-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='background')),
                ('alt', models.CharField(max_length=100)),
                ('pk_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.ModelConfig')),
            ],
        ),
    ]
